export { default as HomeHero } from './home/Hero'
export { default as HomeCTA } from './home/CTA'
export { default as Footer } from './Footer'
export { default as Navbar } from './Navbar'
export { default as HomeAbout } from './home/AboutSection'