export { default as ContactHero }from './contact/Hero'
export { default as HomeDevotionalCTA} from './home/DevotionalCTA'
export { default as HomeHero } from './home/Hero'
export { default as CTA } from './CTA'
export { default as Footer } from './Footer'
export { default as Navbar } from './Navbar'
export { default as HomeAbout } from './home/AboutSection'
export { default as HomeTestimonies } from './home/Testimonies'